version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: python manage.py runserver 0.0.0.0:8000

  celery_worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    command: celery -A cryptopilot worker --loglevel=info

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: 