# Generated by Django 5.0.1 on 2025-05-10 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_running", models.BooleanField(default=False)),
                ("trading_mode", models.CharField(default="paper", max_length=10)),
                (
                    "max_daily_loss",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
                ),
                (
                    "position_size",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
                ),
                (
                    "stop_loss_pct",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
                ),
                (
                    "take_profit_pct",
                    models.DecimalField(decimal_places=2, default=4.0, max_digits=5),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Bot Settings",
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=18)),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=18)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                (
                    "pnl",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                ("entry_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("stop_loss", models.DecimalField(decimal_places=8, max_digits=18)),
                ("take_profit", models.DecimalField(decimal_places=8, max_digits=18)),
            ],
            options={
                "ordering": ["-entry_time"],
            },
        ),
        migrations.CreateModel(
            name="TradingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("base_asset", models.CharField(max_length=10)),
                ("quote_asset", models.CharField(max_length=10)),
                ("min_qty", models.DecimalField(decimal_places=8, max_digits=18)),
                ("price_precision", models.IntegerField()),
                ("qty_precision", models.IntegerField()),
                ("last_price", models.DecimalField(decimal_places=8, max_digits=18)),
                ("volume_24h", models.DecimalField(decimal_places=8, max_digits=24)),
                (
                    "price_change_24h",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-volume_24h"],
            },
        ),
        migrations.CreateModel(
            name="WalletSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "total_balance_usdt",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                ("daily_pnl", models.DecimalField(decimal_places=8, max_digits=18)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
